source 'https://rubygems.org'

gem 'jekyll', '~> 3.9.5'
gem 'jekyll-feed'
gem 'jekyll-sitemap'
gem 'jekyll-redirect-from'
gem 'webrick', '~> 1.8'
gem 'kramdown-parser-gfm'
gem 'csv'
gem 'base64'
gem 'bigdecimal'
